name: Build LaTeX document

on: 
  push:
  pull_request:
    types:
      - closed
    branches:
      - master



jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2


      - name: Compile LaTeX document Syllabus
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Syllabus/

      - name: Compile LaTeX document Introduction
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Introduction/

      - name: Compile LaTeX document AlgebraOfTransformations
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/AlgebraOfTransformations/

      - name: Compile LaTeX document Linkages3D
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Linkages3D/

      - name: Compile LaTeX document Jacobians
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Jacobians/

      - name: Compile LaTeX document Subspaces
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Subspaces/

      - name: Compile LaTeX document InverseKinematics
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/InverseKinematics/

      - name: Compile LaTeX document KinematicsAndTasks
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/KinematicsAndTasks/

      - name: Compile LaTeX document DynamicsManipulatorEq
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/DynamicsManipulatorEq/

      - name: Compile LaTeX document ControlPDLyapunov
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/ControlPDLyapunov/

      - name: Compile LaTeX document ForceControl
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/ForceControl/

      - name: Compile LaTeX document InverseKinematics
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/InverseKinematics/




      - name: Save Syllabus artifact
        uses: actions/upload-artifact@v1
        with:
          name: Syllabus.pdf
          path: Syllabus/main.pdf

      - name: Save Introduction artifact
        uses: actions/upload-artifact@v1
        with:
          name: Introduction.pdf
          path: Slides/Introduction/main.pdf

      - name: Save AlgebraOfTransformations artifact
        uses: actions/upload-artifact@v1
        with:
          name: AlgebraOfTransformations.pdf
          path: Slides/AlgebraOfTransformations/main.pdf

      - name: Save Linkages3D artifact
        uses: actions/upload-artifact@v1
        with:
          name: Linkages3D.pdf
          path: Slides/Linkages3D/main.pdf

      - name: Save Jacobians artifact
        uses: actions/upload-artifact@v1
        with:
          name: Jacobians.pdf
          path: Slides/Jacobians/main.pdf

      - name: Save Subspaces artifact
        uses: actions/upload-artifact@v1
        with:
          name: Subspaces.pdf
          path: Slides/Subspaces/main.pdf

      - name: Save InverseKinematics artifact
        uses: actions/upload-artifact@v1
        with:
          name: InverseKinematics.pdf
          path: Slides/InverseKinematics/main.pdf

      - name: Save KinematicsAndTasks artifact
        uses: actions/upload-artifact@v1
        with:
          name: KinematicsAndTasks.pdf
          path: Slides/KinematicsAndTasks/main.pdf

      - name: Save DynamicsManipulatorEq artifact
        uses: actions/upload-artifact@v1
        with:
          name: DynamicsManipulatorEq.pdf
          path: Slides/DynamicsManipulatorEq/main.pdf

      - name: Save ControlPDLyapunov artifact
        uses: actions/upload-artifact@v1
        with:
          name: ControlPDLyapunov.pdf
          path: Slides/ControlPDLyapunov/main.pdf

      - name: Save ForceControl artifact
        uses: actions/upload-artifact@v1
        with:
          name: ForceControl.pdf
          path: Slides/ForceControl/main.pdf

      - name: Save InverseKinematics artifact
        uses: actions/upload-artifact@v1
        with:
          name: InverseKinematics.pdf
          path: Slides/InverseKinematics/main.pdf






      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add Syllabus/main.pdf
          git add Slides/Introduction/main.pdf
          git add Slides/AlgebraOfTransformations/main.pdf
          git add Slides/Linkages3D/main.pdf
          git add Slides/Jacobians/main.pdf
          git add Slides/Subspaces/main.pdf
          git add Slides/InverseKinematics/main.pdf
          git add Slides/KinematicsAndTasks/main.pdf
          git add Slides/DynamicsManipulatorEq/main.pdf
          git add Slides/ControlPDLyapunov/main.pdf
          git add Slides/ForceControl/main.pdf
          git add Slides/InverseKinematics/main.pdf




          git commit -m "Update compiled PDFs"
          git push
